//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campagnes.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string Objet { get; set; }
        public string Corps { get; set; }
        public int IdCategorieVip { get; set; }
        public int IdEvenement { get; set; }
    
        public virtual CategorieVip CategorieVip { get; set; }
        public virtual Evenement Evenement { get; set; }
    }
}
